### ISSUE TITLE
Can't get Luau to work

### ISSUE THREAD

**Issue by YosseufDEV** [lopi-py/luau-lsp.nvim#11]

**Comment by YosseufDEV** [comment]
Pretty much the title says its all I can't get the lsp server to work here's my config
`
local lsp = require("lsp-zero")
require('mason').setup({})


lsp.preset("recommended")

require("mason-lspconfig").setup_handlers({
    luau_lsp = function()
        require("luau-lsp").luau_lsp.setup({
            server = {
                filetypes = { "luau" }, -- default is { "luau" }
                capabilities = vim.lsp.protocol.make_client_capabilities(),
                root_dir = function(path)
                    local util = require("lspconfig.util")
                    return util.find_git_ancestor(path)
                    or util.root_pattern(
                    ".luaurc",
                    "selene.toml",
                    "stylua.toml",
                    "aftman.toml",
                    "wally.toml",
                    "mantle.yml",
                    "*.project.json"
                    )(path)
                end,
            },
            settings = {},
            types = {
                roblox = true,
            },
            sourcemap = {
                enable = true,
                rojo_path = "rojo",
            },
        })
    end,
})

require('mason-lspconfig').setup({
  ensure_installed = {
      'luau_lsp',
  },
  automatic_installation = true,
  handlers = { lsp.default_setup },
})

`
am I doing something wrong?

**Comment by lopi-py** [comment]
Define de plugin before mason lspconfig (or put as a dependency), also your setup call is wrong, check the readme.

**Comment by YosseufDEV** [comment]
Hey thanks for the reply yeah I'm pretty sure I done that in the code I sent or am I doing something wrong?

**Comment by lopi-py** [comment]
Hello, yes
* your setup call is `require("luau-lsp").setup`not `require("luau-lsp").luau_lsp.setup`
* `settings` table should be under the `server` table
* try putting this plugin as a dependency of mason-lspconfig.nvim

**Comment by YosseufDEV** [comment]
Oh I see now I guess I kinda did that by mistake as I was exploring on why it didn't work yesterday but It's working now Thanks!
