### ISSUE TITLE
Client luau_lsp quit with exit code 1 and signal 0

### ISSUE THREAD

**Issue by CompletedLoop** [lopi-py/luau-lsp.nvim#15]
Not aware if I set this up right but everytime I open up a luau file in my game project I keep getting this:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/ed96ab5f-cd4e-4201-8467-f245f5a0f178)
Ive called :LuauRegenerateSourcemap but that doesnt fix it either.
lsp.log:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/f3145fbf-1c09-4b16-965b-2ea75b45f71a)

And ive just copied and pasted the setup from the readme

**Comment by CompletedLoop** [comment]
new to neovim and im user Lunarvim and this is how im loading in the plugin:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/a567bc50-962e-4118-b126-bfe1a969ae3c)

If I remove the config function it works fine but I get no Sourcemap generation and the plugin stops working.

Neovim 0.10

**Comment by lopi-py** [comment]
Your config seems right in this case, just remove the `opts` field in the plugin spec. The error `The command line is too long` is unrelated to this plugin, but seems more like a Windows or mason issue, I think it is more appropriate to ask for help in the [mason repo](https://github.com/williamboman/mason.nvim) or google a solution. Just curious, do other lsp's work or is the issue only with luau-lsp?

**Comment by CompletedLoop** [comment]
> Your config seems right in this case, just remove the `opts` field in the plugin spec. The error `The command line is too long` is unrelated to this plugin, but seems more like a Windows or mason issue, I think it is more appropriate to ask for help in the [mason repo](https://github.com/williamboman/mason.nvim) or google a solution. Just curious, do other lsp's work or is the issue only with luau-lsp?

Its just luau. 

Whats confusing is if I just load the plugin by itself I get lsp but, the commands disappear. If I try to setup the lsp then I get no lsp but I get the luau commands.

**Comment by lopi-py** [comment]
Yeah, I don't think it is related to this plugin, try checking [this Windows guide](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#how-to-work-around-the-limitation), maybe your PATH variable is too long

**Comment by CompletedLoop** [comment]
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/40706c84-bc01-47fa-afe8-77f0a5be7a35)
So It appears this is over the character limit:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/278ddbee-d9dc-4b61-93a6-291127a71a92)
And windows says the limit is 8192.

Not sure what to do exactly to reduce the characters in the command.

**Comment by lopi-py** [comment]
Try to turn off the fflag sync option

**Comment by CompletedLoop** [comment]
> Try to turn off the fflag sync option

This worked appreciate it.

Should probably put this in the readme if people are experiencing the same issue.
