### ISSUE TITLE
luau-lsp mistakenly identifies src/ as root_dir whenever there's a luaurc file under it

### ISSUE THREAD

**Issue by Eggflaw** [lopi-py/luau-lsp.nvim#19]
I currently have luaurc file in my project but when I put it inside the src directory the root directory becomes `{project}/src` instead of `{project}` 

This does not happen when I put it outside of `src`
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/108559753/4020d3d7-e70d-46c9-af5d-ae7de170f0cb)

Problems caused
- Failed to load sourcemap for workspace error
- misalignment with string requires (see above)

**Comment by lopi-py** [comment]
What is your use case for `.luaurc` to be under src/ instead of the root dir? `.luaurc` is used as a root marker

**Comment by Eggflaw** [comment]
I have no specific reason but I am using [roblox-project-template](https://github.com/grilme99/roblox-project-template) to create my project on top of.
In that repo, the `.luaurc` file is under src/. I don't why it's in there but I assumed it worked fine for them to not cause any issues
