### ISSUE TITLE
Trying to use without Roblox

### ISSUE THREAD

**Issue by BenMcAvoy** [lopi-py/luau-lsp.nvim#2]
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/143108602/3e0a6c4b-3b1c-468a-86bc-73c88f7bf9a6)

I have `Rojo` installed. I don't have Roblox installed as I'm on linux and I don't want to have anything to do with Roblox at all, just raw Luau. How can I achieve this?

![image](https://github.com/lopi-py/luau-lsp.nvim/assets/143108602/acf7fbac-6d2a-457c-8b16-4235b3e3dba6)

It seems to at least work for the most part ignoring the errors.

Here is my lspconfig:

```lua
local masonlsp = require("mason-lspconfig")

masonlsp.setup()

masonlsp.setup_handlers {
  luau_lsp = function()
    require("luau-lsp").setup {
      server = { -- options passed to `require("lspconfig").luau_lsp.setup`
        filetypes = { "lua", "luau" }, -- default is { "luau" }
        settings = {
          types = {
            roblox = false,
          }
        },
      },
    }
  end,
}

local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

local servers = { "html", "cssls", "tsserver", "clangd", "rust_analyzer" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

**Comment by lopi-py** [comment]
Note that roblox related settings are not server specific, check the readme, you should do like this:
```lua
require("luau-lsp").setup {
  sourcemap = {
    enable = false, -- disable sourcemap generation (rojo)
  },
  types = {
    roblox = false, -- disable roblox api
  },
}
```

**Comment by lopi-py** [comment]
Just in case, for future issues, seems like your rojo version is some old and does not support `--watch` flag on `sourcemap` command

**Comment by BenMcAvoy** [comment]
I installed it with `cargo install rojo --version ^7` (it's not in my repos) so is that an outdated version? It's what was on the docs

**Comment by BenMcAvoy** [comment]
Another question I have is why `rojo` is required. If I'm doing nothing to do with Roblox, what is it used for?

**Comment by lopi-py** [comment]
Rojo is not required at all, you had the incorrect settings, check my previous comments so you can set it up properly and no longer depend of rojo

**Comment by BenMcAvoy** [comment]
Oh I see, I forgot the sourcemap disable. Thanks so much! Sorry for being stupid :sweat_smile:
