### ISSUE TITLE
Quit with exit code 3221225477 and signal 0.

### ISSUE THREAD

**Issue by CompletedLoop** [lopi-py/luau-lsp.nvim#24]
This started happening and I cannot for the life of me find a solution to this.
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/2870a1a6-9df1-42ec-a695-41d3e34fb9b8)
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/bb2d2b19-dd2f-43be-aaac-80f7e6235cec)
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/8da094d5-4b4a-466f-bf4b-3ee355a79e7a)
LspLog:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/5d05f681-4b5e-4d2b-8405-0d85bbd8332c)

**Comment by lopi-py** [comment]
This crash is happening with luau-lsp `1.31.0`, using a previous version should work. If you are using mason, run `:MasonInstall luau-lsp@1.30.1`.

**Comment by CompletedLoop** [comment]
This worked but now I am getting this error:
![image](https://github.com/lopi-py/luau-lsp.nvim/assets/163626738/b09a404a-65b9-4193-a50d-9f4e0f2e3428)

**Comment by lopi-py** [comment]
It seems like you called `lspconfig.luau_lsp.setup` somewhere, your LspInfo luau-lsp's command does not match with luau-lsp.nvim.

**Comment by CompletedLoop** [comment]
I cannot find anywhere where this is called. Its not in my config and its not in my distro's core either. I am using vscodes's search.
![image](https://github.com/user-attachments/assets/f5da361a-cd76-461b-80ba-9032f60d5ab7)

**Comment by lopi-py** [comment]
@CompletedLoop I think your distro is calling that somewhere. I've added some health checks, so try running `:checkhealth luau-lsp` to check the plugin status.
