### ISSUE TITLE
Incorrect root_dir rojo project file detection

### ISSUE THREAD

**Issue by jaschutte** [lopi-py/luau-lsp.nvim#28]
At line 51 of config.lua it uses the following regex:
```lua
        return name:match ".*%.project.json$"
```
It should be:
```lua
        return name:match ".*%.project%.json$"
```

The one currently in the main forgot an `%`, allow the dot to match any character.

Yes, this is nit picky beyond relief but hey, someone had to mention it.

**Comment by lopi-py** [comment]
Oh, indeed, `.` means all characters, so we need to escape it with `%`
