### ISSUE TITLE
isIgnoredFile failed

### ISSUE THREAD

**Issue by Zead0n** [lopi-py/luau-lsp.nvim#30]
Started neovim on the directory with default.project.json file but when attempting to edit a lua/luau file it displays:
![image](https://github.com/user-attachments/assets/c1aedea1-7a0c-4378-8728-1c7c828f936a)

I tried to look into why by analyzing the luau-lsp source code but I'm not proficient in C++ so I can't tell if it's a problem with the lsp. This wasn't an issue before so I've tried rolling back to [1.4.0](https://github.com/lopi-py/luau-lsp.nvim/releases/tag/v1.4.0), installing luau-lsp locally instead of mason, and using a previous version of the lsp ([1.32.2](https://github.com/JohnnyMorganz/luau-lsp/releases/tag/1.32.2)) but they didn't fix the problem. However, when I use the "Luau Language Server" extention in vscode there seems to be no issue, so I thought it could be something with the plugin or perhaps my system/configs.

### Import and configs:
```lua
-- nvim\lua\custom\plugins\luau-lsp.lua
return {
  'lopi-py/luau-lsp.nvim',
  lazy = false,
  opts = {},
  dependencies = {
    'neovim/nvim-lspconfig',
    'nvim-lua/plenary.nvim',
  },
}
```

```lua
-- nvim\init.lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = vim.tbl_deep_extend('force', capabilities, require('cmp_nvim_lsp').default_capabilities())

require('mason-lspconfig').setup_handlers {
  luau_lsp = function()
    require('luau-lsp').setup {
      platform = {
        type = 'roblox',
      },
      sourcemap = {
        enabled = true,
        autogenerate = true, -- automatic generation when the server is attached
        rojo_project_file = 'luau.project.json',
      },
      server = {
        capabilities = capabilities,
      },
    }
  end,
}

require('mason-lspconfig').setup {
  handlers = {
    function(server_name)
      -- NOTE: Custom luau-lsp config is already setup previously
      if server_name == 'luau_lsp' then
        return
      end

      local server = servers[server_name] or {} -- 'servers' is a table that holds other lsp's and their configs (rust-analyzer, gopls, etc.)
      server.capabilities = vim.tbl_deep_extend('force', {}, capabilities, server.capabilities or {})

      require('lspconfig')[server_name].setup(server)
    end,
  },
}
```

### checkhealth:
![image](https://github.com/user-attachments/assets/27ef957a-0f46-4824-8c96-eeb0145beaff)

### LuauLsp log:
![image](https://github.com/user-attachments/assets/f907966a-60c3-4b1b-a662-04f04c5be7fe)

### System
Windows 10 Home 22H2
Neovim 10.1

**Comment by lopi-py** [comment]
This is an [issue with luau-lsp](https://github.com/JohnnyMorganz/luau-lsp/issues/752), maybe you could give some input there. I'm not sure why it happens on Neovim and not on VSCode. I'm not able to trigger this on Windows 11 and Neovim 0.10.1, but I've seen people using luau-lsp `1.32.1` with no complains.

**Comment by Zead0n** [comment]
The workaround works. I might look into the luau-lsp commit history to find the lastest commit before the bug happens in hopes I can at least find the issue. if not, I hope someone else can. Thanks for the quick reply! I'll close this since it's not a bug with the plugin.
