### ISSUE TITLE
Plugin not detecting types.

### ISSUE THREAD

**Issue by s2xon** [lopi-py/luau-lsp.nvim#35]
Using [this](https://github.com/dphfox/Fusion/blob/29fc29ada061415ed805bc60bd63a2dfba4fdae4/src/Types.luau#L4) file. Which is a link to the Fusion types. I still get Type errors in my code when working with the fusion frame work. I have tried using both .luau and .d.luau for the path

```lua
types = {
      roblox_security_level = "PluginSecurity",
      definition_files = { "~/Downloads/Types.d.luau" },
    },
```

**Comment by s2xon** [comment]
I may be doing something incorrect though so let me know! Thanks.

**Comment by lopi-py** [comment]
Hello, please provide the output of the following commands
- `:LuauLsp log`
- `:checkhealth luau-lsp`

**Comment by s2xon** [comment]
Will do, give me a few. Thanks for your response!

**Comment by s2xon** [comment]
I thought I would let you know as for LuauLsp log all I have is it looking for a connection for the Roblox plugin (idk how that works)

As for checkhealth luau-lsp everything is good and lspconfig.luau-lsp is not called.

**Comment by s2xon** [comment]
I will send screen shots.

**Comment by lopi-py** [comment]
Just to make sure, did you put the config shown in `.nvim.lua` or in your `nvim` config directory?

**Comment by s2xon** [comment]
https://github.com/s2xon/nvim
Search luau-lsp.

![Screenshot 2024-11-19 at 2 35 17 PM](https://github.com/user-attachments/assets/20d74a33-393b-4528-82a6-d349afa70964)
![Screenshot 2024-11-19 at 2 35 00 PM](https://github.com/user-attachments/assets/4da401c2-c291-4328-9466-d170827d4c4a)
![Screenshot 2024-11-19 at 2 34 31 PM](https://github.com/user-attachments/assets/3236dbab-edfd-4fac-ab97-36585e32a27b)

**Comment by lopi-py** [comment]
Oh so you are accessing `Fusion.Type` members. If you are using wally, it doesn't export types (so hence the unknown type error). You might be looking for [wally-package-types](https://github.com/JohnnyMorganz/wally-package-types), you need to run the commands after every `wally install`

**Comment by s2xon** [comment]
Thanks so much
