### ISSUE TITLE
Plugin error on load: "attempt to call field 'list_contains' (a nil value)"

### ISSUE THREAD

**Issue by Abstract-Everything** [lopi-py/luau-lsp.nvim#8]
I recently upgraded and upon opening a luau file I am getting the error in the title. Based on a quick search from the neovim codebase the 'list_contains' function does not appear to be present on 'v0.9.5'

function in master: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/shared.lua#L308
same file in v0.9.5: https://github.com/neovim/neovim/blob/v0.9.5/runtime/lua/vim/shared.lua#L449

I am not sure how this should be resolved perhaps it should be clarified with the neovim team as to why this function is not in stable and whether it is planned to be.

**Comment by lopi-py** [comment]
Hmm thats weird, It seems like it was introduced [9 months ago](https://github.com/neovim/neovim/commit/4d04feb6629cb049cb2a13ba35f0c8d3c6b67ff4). So it should definitely be shipped with v0.9.5?

**Comment by lopi-py** [comment]
I've pushed a fix recently. Feel free to reopen if you still have a related issue. Thanks for reporting.
